# Generated by Django 2.1.1 on 2018-11-07 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='Module',
            new_name='module',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='project',
        ),
    ]
