# Generated by Django 2.1.1 on 2018-12-15 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0007_testresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresult',
            old_name='failures',
            new_name='failure',
        ),
    ]
