# Generated by Django 2.1.4 on 2018-12-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itest', '0042_auto_20180322_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
