# Generated by Django 2.1.1 on 2019-04-19 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0003_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='interface',
            new_name='interfaces',
        ),
    ]
