# Generated by Django 2.1.1 on 2019-04-19 14:39

from django.db import migrations
import interface_app.fields.model.object_field


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0004_auto_20190419_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='assertion',
            field=interface_app.fields.model.object_field.ObjectField(default=[], verbose_name='assertion'),
        ),
    ]
