# Generated by Django 2.2.1 on 2019-06-01 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0005_auto_20190419_2239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
